name: 'PR Labels checker'
description: 'Check if a merged pull request contain specified labels'
inputs:
  labels:
    description: 'Labels the pull request should have'
    required: true
outputs:
  labelsMatched:
    description: 'true if the pull request contains the input labels'
runs:
  using: 'node12'
  main: 'dist/index.js'
